routes/web.php
<?php

use App\Http\Controllers\BadgeController;
use App\Http\Controllers\FeedController;
use App\Http\Controllers\MeetupController;
use App\Http\Controllers\MilestoneController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PatronController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebhookController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes();
Auth::routes(['verify' => true]);

// Social Auth
Route::get('login/{provider}', [SocialController::class, 'redirect']);
Route::get('login/{provider}/callback', [SocialController::class, 'callback']);

// 404 Fallback
Route::fallback(function () {
    return response()->view('errors.404', [], 404);
});

// Suspended
Route::view('suspended', 'auth.suspended')
    ->name('suspended');

// Home/Dashboard/Landing
Route::view('/', 'home.home')->name('home');

// Explore
Route::group(['prefix' => 'explore', 'as' => 'explore.'], function () {
    Route::view('', 'explore.explore')
        ->name('explore');
    Route::view('/makers', 'explore.makers')
        ->name('makers');
});

// User
Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
    Route::get('', [UserController::class, 'profile'])
        ->name('done');
    Route::get('pending', [UserController::class, 'profile'])
        ->name('pending');
    Route::get('products', [UserController::class, 'profile'])
        ->name('products');
    Route::get('questions', [UserController::class, 'profile'])
        ->name('questions');
    Route::get('answers', [UserController::class, 'profile'])
        ->name('answers');
    Route::get('milestones', [UserController::class, 'profile'])
        ->name('milestones');
    Route::get('following', [UserController::class, 'profile'])
        ->name('following');
    Route::get('followers', [UserController::class, 'profile'])
        ->name('followers');
    Route::get('stats', [UserController::class, 'profile'])
        ->name('stats');
    Route::get('/json', [UserController::class, 'json'])
        ->name('json');
});

// Settings
Route::group([
    'prefix'     => 'settings',
    'as'         => 'user.settings.',
    'middleware' => ['auth'],
], function () {
    Route::get('', [UserController::class, 'profileSettings'])
        ->name('profile');
    Route::get('account', [UserController::class, 'accountSettings'])
        ->name('account');
    Route::get('appearance', [UserController::class, 'appearanceSettings'])
        ->name('appearance');
    Route::get('products', [UserController::class, 'productsSettings'])
        ->name('products');
    Route::get('patron', [UserController::class, 'patronSettings'])
        ->name('patron');
    Route::get('password', [UserController::class, 'passwordSettings'])
        ->name('password');
    Route::get('notifications', [UserController::class, 'notifySettings'])
        ->name('notifications');
    Route::get('integrations', [UserController::class, 'integrationsSettings'])
        ->name('integrations');
    Route::get('api', [UserController::class, 'apiSettings'])
        ->name('api');
    Route::get('sessions', [UserController::class, 'sessionsSettings'])
        ->name('sessions');
    Route::get('logs', [UserController::class, 'logsSettings'])
        ->name('logs');
    Route::get('data', [UserController::class, 'dataSettings'])
        ->name('data');
    Route::get('delete', [UserController::class, 'deleteSettings'])
        ->name('delete');
    Route::get('export/account', [UserController::class, 'exportAccount'])
        ->name('export.account');
    Route::get('export/logs', [UserController::class, 'exportLogs'])
        ->name('export.logs');
});

// Notifications
Route::group([
    'prefix'     => 'notifications',
    'as'         => 'notifications.',
    'middleware' => ['auth'],
], function () {
    Route::view('', 'notifications.unread')
        ->name('unread');
    Route::view('all', 'notifications.all')
        ->name('all');
});

// Webhooks
Route::group(['prefix' => 'webhook'], function () {
    Route::post('web/{token}', [WebhookController::class, 'web']);
});

// Product
Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
    Route::get('', [ProductController::class, 'profile'])
        ->name('done');
    Route::get('pending', [ProductController::class, 'profile'])
        ->name('pending');
    Route::get('updates', [ProductController::class, 'profile'])
        ->name('updates');
    Route::get('subscribers', [ProductController::class, 'profile'])
        ->name('subscribers');
    Route::get('edit', [ProductController::class, 'edit'])
        ->middleware('auth')
        ->name('edit');
    Route::get('verify', [ProductController::class, 'verify'])
        ->middleware('auth')
        ->name('verify');
});

// Products
Route::group([
    'prefix' => 'products',
    'as'     => 'products.',
], function () {
    Route::get('', [ProductController::class, 'newest'])
        ->name('newest');
    Route::get('launched', [ProductController::class, 'launched'])
        ->name('launched');
    Route::view('new', 'products.new')
        ->middleware('auth')
        ->name('new');
});

// Question
Route::group([
    'prefix' => 'question',
    'as'     => 'question.',
], function () {
    Route::get('{slug}', [QuestionController::class, 'question'])
        ->name('question');
    Route::get('{slug}/edit', [QuestionController::class, 'edit'])
        ->middleware('auth')
        ->name('edit');
});

// Questions
Route::group([
    'prefix' => 'questions',
    'as'     => 'questions.',
], function () {
    Route::get('', [QuestionController::class, 'newest'])
        ->name('newest');
    Route::get('unanswered', [QuestionController::class, 'unanswered'])
        ->name('unanswered');
    Route::get('popular', [QuestionController::class, 'popular'])
        ->name('popular');
    Route::view('new', 'question.new')
        ->middleware('auth')
        ->name('new');
});

// Milestone
Route::group([
    'prefix' => 'milestones',
    'as'     => 'milestones.',
], function () {
    Route::get('', [MilestoneController::class, 'opened'])
        ->name('opened');
    Route::get('closed', [MilestoneController::class, 'closed'])
        ->name('closed');
    Route::view('new', 'milestones.new')
        ->middleware('auth')
        ->name('new');
    Route::get('{milestone}/edit', [MilestoneController::class, 'edit'])
        ->middleware('auth')
        ->name('edit');
    Route::get('{milestone}', [MilestoneController::class, 'milestone'])
        ->name('milestone');
});

// Badges
Route::group([
    'prefix' => 'badges',
    'as'     => 'badges.',
], function () {
    Route::view('', 'badges.badges')
        ->middleware('feature:badges')
        ->name('badges');
    Route::view('new', 'badges.new')
        ->middleware('staff_mode')
        ->name('new');
    Route::get('{slug}/edit', [BadgeController::class, 'edit'])
        ->middleware('staff_mode')
        ->name('edit');
    Route::get('{slug}', [BadgeController::class, 'badge'])
        ->middleware('feature:badges')
        ->name('badge');
});

// Search
Route::group([
    'prefix' => 'search',
    'as'     => 'search.',
], function () {
    Route::get('', [SearchController::class, 'search'])
        ->name('home');
    Route::get('tasks', [SearchController::class, 'tasks'])
        ->name('tasks');
    Route::get('comments', [SearchController::class, 'comments'])
        ->name('comments');
    Route::get('questions', [SearchController::class, 'questions'])
        ->name('questions');
    Route::get('answers', [SearchController::class, 'answers'])
        ->name('answers');
    Route::get('products', [SearchController::class, 'products'])
        ->name('products');
    Route::get('users', [SearchController::class, 'users'])
        ->name('users');
});

// Stafftools
Route::group([
    'prefix'     => 'stafftools',
    'as'         => 'staff.',
    'middleware' => ['staff_mode'],
], function () {
    Route::view('', 'staff.stats')
        ->middleware('password.confirm')
        ->name('stats');
    Route::view('users', 'staff.users')
        ->middleware('password.confirm')
        ->name('users');
    Route::view('tasks', 'staff.tasks')
        ->middleware('password.confirm')
        ->name('tasks');
    Route::view('activities', 'staff.activities')
        ->middleware('password.confirm')
        ->name('activities');
    Route::view('products', 'staff.products')
        ->middleware('password.confirm')
        ->name('products');
    Route::view('features', 'staff.features')
        ->middleware('password.confirm')
        ->name('features');
    Route::view('jobs', 'staff.jobs')
        ->middleware('password.confirm')
        ->name('jobs');
});

// Patron
Route::group([
    'prefix' => 'patron',
    'as'     => 'patron.',
], function () {
    Route::view('', 'pages.patron')
        ->name('home');
});

// Paddle Integration
Route::post('paddle/webhook', [PatronController::class, 'handleWebhook'])
    ->name('paddle.webhook');

// Dark mode
Route::get('darkmode', [UserController::class, 'darkMode'])
    ->name('darkmode')
    ->middleware('auth');

// Single Task and comment
Route::group(['prefix' => 'task'], function () {

app/Http/Controllers/MilestoneController.php
<?php

namespace App\Http\Controllers;

use App\Models\Milestone;
use Illuminate\View\View;

class MilestoneController extends Controller
{
    public function opened(): View
    {
        return view('milestones.milestones', [
            'type' => 'milestones.opened',
        ]);
    }

    public function closed(): View
    {
        return view('milestones.milestones', [
            'type' => 'milestones.closed',
        ]);
    }

    public function milestone(Milestone $milestone): View
    {
        $response = [
            'type'      => 'milestones.milestone',
            'milestone' => $milestone,
        ];
        if (
            auth()->check() && auth()->user()->id === $milestone->user->id or
            auth()->check() && auth()->user()->staff_mode
        ) {
            return view('milestones.milestone', $response);
        }

        if ($milestone->user->spammy or $milestone->user->is_private) {
            return abort(404);
        }

        return view('milestones.milestone', $response);
    }

    public function edit(Milestone $milestone): View
    {
        if (
            auth()->check() && auth()->user()->id === $milestone->user->id or
            auth()->check() && auth()->user()->staff_mode
        ) {
            return view('milestones.edit', [
                'milestone' => $milestone,
            ]);
        }

        return abort(404);
    }

    public function popover(Milestone $milestone): View
    {
        return view('milestones.popover', [
            'milestone' => $milestone,
        ]);
    }
}

app/Http/Livewire/Milestone/CreateMilestone.php
<?php

namespace App\Http\Livewire\Milestone;

use Illuminate\Support\Facades\Gate;
use Livewire\Component;

class CreateMilestone extends Component
{
    public $name;
    public $description;
    public $startDate;
    public $endDate;

    public function submit()
    {
        if (Gate::denies('create')) {
            return toast($this, 'error', config('taskord.toast.deny'));
        }

        $this->validate([
            'name'        => ['required', 'min:3', 'max:150'],
            'description' => ['required', 'min:3', 'max:10000'],
        ]);

        $milestone = auth()->user()->milestones()->create([
            'name'        => $this->name,
            'description' => $this->description,
            'start_date'  => $this->startDate,
            'end_date'    => $this->endDate,
        ]);
        $this->emit('refreshMilestones');

        loggy(request(), 'Milestone', auth()->user(), "Created a new milestone | Milestone ID: {$milestone->id}");

        return redirect()->route('milestones.milestone', ['milestone' => $milestone]);
    }
}

app/Http/Livewire/Milestone/EditMilestone.php
<?php

namespace App\Http\Livewire\Milestone;

use App\Models\Milestone;
use Illuminate\Support\Facades\Gate;
use Livewire\Component;

class EditMilestone extends Component
{
    public Milestone $milestone;
    public $name;
    public $description;
    public $startDate;
    public $endDate;

    protected $rules = [
        'name'        => ['required', 'min:3', 'max:150'],
        'description' => ['required', 'min:3', 'max:10000'],
    ];

    public function mount($milestone)
    {
        $this->milestone = $milestone;
        $this->name = $milestone->name;
        $this->description = $milestone->description;
        $this->startDate = $milestone->start_date ? carbon($milestone->start_date)->format('Y-m-d') : null;
        $this->endDate = $milestone->end_date ? carbon($milestone->end_date)->format('Y-m-d') : null;
    }

    public function updated($field)
    {
        if (! auth()->check()) {
            return toast($this, 'error', config('taskord.toast.deny'));
        }

        $this->validateOnly($field);
    }

    public function submit()
    {
        if (Gate::denies('edit/delete', $this->milestone)) {
            return toast($this, 'error', config('taskord.toast.deny'));
        }

        $this->validate();

        $milestone = Milestone::where('id', $this->milestone->id)->firstOrFail();

        $milestone->name = $this->name;
        $milestone->description = $this->description;
        $milestone->start_date = $this->startDate ? $this->startDate : null;
        $milestone->end_date = $this->startDate ? $this->endDate : null;
        $milestone->save();
        $this->emit('refreshMilestones');

        loggy(request(), 'Milestone', auth()->user(), "Updated a milestone | Milestone ID: {$milestone->id}");

        return redirect()->route('milestones.milestone', ['milestone' => $milestone]);
    }
}

app/Http/Livewire/Milestone/SingleMilestone.php
<?php

namespace App\Http\Livewire\Milestone;

use App\Models\Milestone;
use DanHarrin\LivewireRateLimiting\Exceptions\TooManyRequestsException;
use DanHarrin\LivewireRateLimiting\WithRateLimiting;
use Helper;
use Illuminate\Support\Facades\Gate;
use Livewire\Component;

class SingleMilestone extends Component
{
    use WithRateLimiting;

    public Milestone $milestone;
    public $type;

    public function mount($milestone, $type)
    {
        $this->milestone = $milestone;
        $this->type = $type;
    }

    public function toggleLike()
    {
        try {
            $this->rateLimit(50);
        } catch (TooManyRequestsException $exception) {
            return toast($this, 'error', config('taskord.error.rate-limit'));
        }

        if (Gate::denies('like/subscribe', $this->milestone)) {
            return toast($this, 'error', config('taskord.toast.deny'));
        }

        Helper::toggleLike($this->milestone, 'MILESTONE');
        $this->emit('milestoneLiked');

        return loggy(request(), 'Milestone', auth()->user(), "Toggled milestone like | Milestone ID: {$this->milestone->id}");
    }

    public function hide()
    {
        if (Gate::denies('staff.ops')) {
            return toast($this, 'error', config('taskord.toast.deny'));
        }

        Helper::hide($this->milestone);
        $this->emit('milestonesHidden');
        loggy(request(), 'Staff', auth()->user(), "Toggled hide milestone | Milestone ID: {$this->milestone->id}");

        return toast($this, 'success', 'Milestone is hidden from public!');
    }

    public function toggleStatus()
    {
        if (! auth()->check()) {
            return toast($this, 'error', config('taskord.toast.deny'));
        }

        if ($this->milestone->status) {
            $this->milestone->status = false;
            $this->milestone->save();
            loggy(request(), 'Milestone', auth()->user(), "Closed the milestone | Milestone ID: {$this->milestone->id}");

            return redirect()->route('milestones.milestone', ['milestone' => $this->milestone]);
        }

        $this->milestone->status = true;
        $this->milestone->save();
        loggy(request(), 'Milestone', auth()->user(), "Opened the milestone | Milestone ID: {$this->milestone->id}");

        return redirect()->route('milestones.milestone', ['milestone' => $this->milestone]);
    }

    public function deleteMilestone()
    {
        if (Gate::denies('edit/delete', $this->milestone)) {
            return toast($this, 'error', config('taskord.toast.deny'));
        }

        loggy(request(), 'Milestone', auth()->user(), "Deleted a milestone | Milestone ID: {$this->milestone->id}");
        $this->milestone->delete();
        $this->emit('refreshMilestones');

        return redirect()->route('milestones.opened');
    }
}

resources/views/milestones/edit.blade.php
@extends('layouts.app')

@section('pageTitle', 'New Milestone ·')

@section('content')
    <div class="container-md">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                @auth
                    @if (!auth()->user()->spammy)
                        <livewire:milestone.edit-milestone :milestone="$milestone" />
                    @else
                        <div class="text-center">
                            <div class="alert alert-danger" role="alert">
                                You can't edit this milestone, because your account has been flagged 😢
                            </div>
                            <a class="btn btn-outline-primary rounded-pill" href="{{ route('home') }}">Go to home</a>
                        </div>
                    @endif
                @endauth
            </div>
        </div>
    </div>
    <x-bottom-footer />
@endsection

resources/views/milestones/milestone.blade.php
@extends('layouts.app')

@if ($milestone->hidden)
    @section('pageTitle', 'Hidden Milestone ·')
@else
    @section('pageTitle', $milestone->name . ' ·')
    @section('title', 'Milestone by @' . $milestone->user->username . ' ·')
    @section('description', $milestone->name)
    @section('image', Helper::getCDNImage($milestone->user->avatar))
    @section('url', url()->current())
@endif

@section('content')
    <div class="container-md">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="mb-4">
                    <livewire:milestone.single-milestone :type="$type" :milestone="$milestone" :wire:key="$milestone->id" />
                </div>
                @livewire('milestone.tasks', [
                'milestone' => $milestone,
                'page' => 1,
                'perPage' => 1
                ])
            </div>
            <div class="col-sm">
                <div class="text-uppercase fw-bold text-secondary pb-2">
                    Created by
                </div>
                <div class="card mb-4">
                    <div class="card-body d-flex align-items-center">
                        <x:shared.user-label-with-bio :user="$milestone->user" />
                    </div>
                </div>
                @if ($milestone->likerscount() > 0)
                    <div class="text-uppercase fw-bold text-secondary pb-2">
                        Liked by
                    </div>
                    <div class="card mb-4">
                        <div class="card-body align-items-center pb-2">
                            @foreach ($milestone->likers as $user)
                                <a title="{{ $user->firstname ? $user->firstname . ' ' . $user->lastname : $user->username }}"
                                    href="{{ route('user.done', ['username' => $user->username]) }}" class="me-1">
                                    <img loading=lazy class="rounded-circle avatar-30 mb-2"
                                        src="{{ Helper::getCDNImage($user->avatar, 80) }}" height="30" width="30"
                                        alt="{{ $user->username }}'s avatar" />
                                </a>
                            @endforeach
                        </div>
                    </div>
                @endif
                <x-footer />
            </div>
        </div>
    </div>
@endsection

resources/views/milestones/milestones.blade.php
@extends('layouts.app')

@if ($type === 'milestones.opened')
    @section('pageTitle', 'Milestones / Opened ·')
    @section('title', 'Milestones / Opened ·')
@else
    @section('pageTitle', 'Milestones / Closed ·')
    @section('title', 'Milestones / Closed ·')
@endif
@section('description', 'Browse milestones.')
@section('image', '')
@section('url', url()->current())

@section('content')
    <div class="container-md">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                @include('milestones.nav')
                @livewire('milestone.milestones', [
                'type' => $type,
                'page' => 1,
                'perPage' => 10
                ])
            </div>
            <div class="col-sm">
                <div class="card mb-4">
                    <div class="card-body">
                        WIP
                    </div>
                </div>
                <x-footer />
            </div>
        </div>
    </div>
@endsection

resources/views/milestones/nav.blade.php
<div class="mb-3">
    <a class="mb-2 btn btn-{{ Route::is('milestones.opened') ? '' : 'outline-' }}primary rounded-pill me-2"
        href="{{ route('milestones.opened') }}">
        Opened
    </a>
    <a class="mb-2 btn btn-{{ Route::is('milestones.closed') ? '' : 'outline-' }}primary rounded-pill me-2"
        href="{{ route('milestones.closed') }}">
        Closed
    </a>
    @auth
        <a href="{{ route('milestones.new') }}" class="mb-2 btn btn-outline-success rounded-pill float-md-end">
            <x-heroicon-o-plus class="heroicon" />
            Create a milestone
        </a>
    @endauth
</div>

resources/views/milestones/new.blade.php
@extends('layouts.app')

@section('pageTitle', 'New Milestone ·')

@section('content')
    <div class="container-md">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                @auth
                    @if (!auth()->user()->spammy)
                        <livewire:milestone.create-milestone />
                    @else
                        <div class="text-center">
                            <div class="alert alert-danger" role="alert">
                                You can't create new milestone, because your account has been flagged 😢
                            </div>
                            <a class="btn btn-outline-primary rounded-pill" href="{{ route('home') }}">Go to home</a>
                        </div>
                    @endif
                @endauth
            </div>
        </div>
    </div>
    <x-bottom-footer />
@endsection

resources/views/milestones/popover.blade.php
<div class="p-3">
    <a class="fw-bold text-dark" href="{{ route('milestones.milestone', ['milestone' => $milestone]) }}">
        {{ Str::words($milestone->name, '10') }}
    </a>
    @if ($milestone->description)
        <div class="mt-2 body-font text-secondary">
            {!! Str::words(markdown($milestone->description), '20') !!}
        </div>
    @endif
    @if ($milestone->start_date or $milestone->end_date)
        @if ($milestone->start_date)
            <div class="mt-3 mb-1">
                <x-heroicon-o-calendar class="heroicon heroicon-18px" />
                Started at <b class="text-dark">{{ carbon($milestone->start_date)->format('M d, Y') }}</b>
            </div>
        @endif
        @if ($milestone->end_date)
            <div>
                @php
                    $past_due = $milestone->end_date < carbon();
                @endphp
                @if ($past_due)
                    <div class="text-danger">
                        <x-heroicon-o-exclamation class="heroicon heroicon-18px" />
                        Past due by <b>{{ carbon($milestone->end_date)->format('M d, Y') }}</b>
                    </div>
                @else
                    <div class="text-dark">
                        <x-heroicon-o-calendar class="heroicon heroicon-18px" />
                        Due by <b>{{ carbon($milestone->end_date)->format('M d, Y') }}</b>
                    </div>
                @endif
            </div>
        @endif
    @endif
    <div class="mt-3">
        <x:shared.user-label-small :user="$milestone->user" />
    </div>
</div>