routes/web.php
<?php

use App\Http\Controllers\BadgeController;
use App\Http\Controllers\FeedController;
use App\Http\Controllers\MeetupController;
use App\Http\Controllers\MilestoneController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PatronController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebhookController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes();
Auth::routes(['verify' => true]);

// Social Auth
Route::get('login/{provider}', [SocialController::class, 'redirect']);
Route::get('login/{provider}/callback', [SocialController::class, 'callback']);

// 404 Fallback
Route::fallback(function () {
    return response()->view('errors.404', [], 404);
});

// Suspended
Route::view('suspended', 'auth.suspended')
    ->name('suspended');

// Home/Dashboard/Landing
Route::view('/', 'home.home')->name('home');

// Explore
Route::group(['prefix' => 'explore', 'as' => 'explore.'], function () {
    Route::view('', 'explore.explore')
        ->name('explore');
    Route::view('/makers', 'explore.makers')
        ->name('makers');
});

// User
Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
    Route::get('', [UserController::class, 'profile'])
        ->name('done');
    Route::get('pending', [UserController::class, 'profile'])
        ->name('pending');
    Route::get('products', [UserController::class, 'profile'])
        ->name('products');
    Route::get('questions', [UserController::class, 'profile'])
        ->name('questions');
    Route::get('answers', [UserController::class, 'profile'])
        ->name('answers');
    Route::get('milestones', [UserController::class, 'profile'])
        ->name('milestones');
    Route::get('following', [UserController::class, 'profile'])
        ->name('following');
    Route::get('followers', [UserController::class, 'profile'])
        ->name('followers');
    Route::get('stats', [UserController::class, 'profile'])
        ->name('stats');
    Route::get('/json', [UserController::class, 'json'])
        ->name('json');
});

// Settings
Route::group([
    'prefix'     => 'settings',
    'as'         => 'user.settings.',
    'middleware' => ['auth'],
], function () {
    Route::get('', [UserController::class, 'profileSettings'])
        ->name('profile');
    Route::get('account', [UserController::class, 'accountSettings'])
        ->name('account');
    Route::get('appearance', [UserController::class, 'appearanceSettings'])
        ->name('appearance');
    Route::get('products', [UserController::class, 'productsSettings'])
        ->name('products');
    Route::get('patron', [UserController::class, 'patronSettings'])
        ->name('patron');
    Route::get('password', [UserController::class, 'passwordSettings'])
        ->name('password');
    Route::get('notifications', [UserController::class, 'notifySettings'])
        ->name('notifications');
    Route::get('integrations', [UserController::class, 'integrationsSettings'])
        ->name('integrations');
    Route::get('api', [UserController::class, 'apiSettings'])
        ->name('api');
    Route::get('sessions', [UserController::class, 'sessionsSettings'])
        ->name('sessions');
    Route::get('logs', [UserController::class, 'logsSettings'])
        ->name('logs');
    Route::get('data', [UserController::class, 'dataSettings'])
        ->name('data');
    Route::get('delete', [UserController::class, 'deleteSettings'])
        ->name('delete');
    Route::get('export/account', [UserController::class, 'exportAccount'])
        ->name('export.account');
    Route::get('export/logs', [UserController::class, 'exportLogs'])
        ->name('export.logs');
});

// Notifications
Route::group([
    'prefix'     => 'notifications',
    'as'         => 'notifications.',
    'middleware' => ['auth'],
], function () {
    Route::view('', 'notifications.unread')
        ->name('unread');
    Route::view('all', 'notifications.all')
        ->name('all');
});

// Webhooks
Route::group(['prefix' => 'webhook'], function () {
    Route::post('web/{token}', [WebhookController::class, 'web']);
});

// Product
Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
    Route::get('', [ProductController::class, 'profile'])
        ->name('done');
    Route::get('pending', [ProductController::class, 'profile'])
        ->name('pending');
    Route::get('updates', [ProductController::class, 'profile'])
        ->name('updates');
    Route::get('subscribers', [ProductController::class, 'profile'])
        ->name('subscribers');
    Route::get('edit', [ProductController::class, 'edit'])
        ->middleware('auth')
        ->name('edit');
    Route::get('verify', [ProductController::class, 'verify'])
        ->middleware('auth')
        ->name('verify');
});

// Products
Route::group([
    'prefix' => 'products',
    'as'     => 'products.',
], function () {
    Route::get('', [ProductController::class, 'newest'])
        ->name('newest');
    Route::get('launched', [ProductController::class, 'launched'])
        ->name('launched');
    Route::view('new', 'products.new')
        ->middleware('auth')
        ->name('new');
});

// Question
Route::group([
    'prefix' => 'question',
    'as'     => 'question.',
], function () {
    Route::get('{slug}', [QuestionController::class, 'question'])
        ->name('question');
    Route::get('{slug}/edit', [QuestionController::class, 'edit'])
        ->middleware('auth')
        ->name('edit');
});

// Questions
Route::group([
    'prefix' => 'questions',
    'as'     => 'questions.',
], function () {
    Route::get('', [QuestionController::class, 'newest'])
        ->name('newest');
    Route::get('unanswered', [QuestionController::class, 'unanswered'])
        ->name('unanswered');
    Route::get('popular', [QuestionController::class, 'popular'])
        ->name('popular');
    Route::view('new', 'question.new')
        ->middleware('auth')
        ->name('new');
});

// Milestone
Route::group([
    'prefix' => 'milestones',
    'as'     => 'milestones.',
], function () {
    Route::get('', [MilestoneController::class, 'opened'])
        ->name('opened');
    Route::get('closed', [MilestoneController::class, 'closed'])
        ->name('closed');
    Route::view('new', 'milestones.new')
        ->middleware('auth')
        ->name('new');
    Route::get('{milestone}/edit', [MilestoneController::class, 'edit'])
        ->middleware('auth')
        ->name('edit');
    Route::get('{milestone}', [MilestoneController::class, 'milestone'])
        ->name('milestone');
});

// Badges
Route::group([
    'prefix' => 'badges',
    'as'     => 'badges.',
], function () {
    Route::view('', 'badges.badges')
        ->middleware('feature:badges')
        ->name('badges');
    Route::view('new', 'badges.new')
        ->middleware('staff_mode')
        ->name('new');
    Route::get('{slug}/edit', [BadgeController::class, 'edit'])
        ->middleware('staff_mode')
        ->name('edit');
    Route::get('{slug}', [BadgeController::class, 'badge'])
        ->middleware('feature:badges')
        ->name('badge');
});

// Search
Route::group([
    'prefix' => 'search',
    'as'     => 'search.',
], function () {
    Route::get('', [SearchController::class, 'search'])
        ->name('home');
    Route::get('tasks', [SearchController::class, 'tasks'])
        ->name('tasks');
    Route::get('comments', [SearchController::class, 'comments'])
        ->name('comments');
    Route::get('questions', [SearchController::class, 'questions'])
        ->name('questions');
    Route::get('answers', [SearchController::class, 'answers'])
        ->name('answers');
    Route::get('products', [SearchController::class, 'products'])
        ->name('products');
    Route::get('users', [SearchController::class, 'users'])
        ->name('users');
});

// Stafftools
Route::group([
    'prefix'     => 'stafftools',
    'as'         => 'staff.',
    'middleware' => ['staff_mode'],
], function () {
    Route::view('', 'staff.stats')
        ->middleware('password.confirm')
        ->name('stats');
    Route::view('users', 'staff.users')
        ->middleware('password.confirm')
        ->name('users');
    Route::view('tasks', 'staff.tasks')
        ->middleware('password.confirm')
        ->name('tasks');
    Route::view('activities', 'staff.activities')
        ->middleware('password.confirm')
        ->name('activities');
    Route::view('products', 'staff.products')
        ->middleware('password.confirm')
        ->name('products');
    Route::view('features', 'staff.features')
        ->middleware('password.confirm')
        ->name('features');
    Route::view('jobs', 'staff.jobs')
        ->middleware('password.confirm')
        ->name('jobs');
});

// Patron
Route::group([
    'prefix' => 'patron',
    'as'     => 'patron.',
], function () {
    Route::view('', 'pages.patron')
        ->name('home');
});

// Paddle Integration
Route::post('paddle/webhook', [PatronController::class, 'handleWebhook'])
    ->name('paddle.webhook');

// Dark mode
Route::get('darkmode', [UserController::class, 'darkMode'])
    ->name('darkmode')
    ->middleware('auth');

// Single Task and comment
Route::group(['prefix' => 'task'], function () {

resources/views/pages/about.blade.php
@extends('layouts.app')

@section('pageTitle', 'About ·')
@section('title', 'About ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
    <div class="container col-lg-6">
        <div class="text-center my-5">
            <img class="mb-3" src="https://ik.imagekit.io/taskordimg/logo_FLhAmih_U.svg" height="70" alt="Taskord Logo">
            <div class="h1">Get things done in public</div>
            <div class="mt-3 h4 lh-sm text-secondary fw-normal" style="letter-spacing:1px">
                Taskord is a community of makers in tech shipping and working together. Makers post their daily tasks and
                grow a network of supportive, like-minded people.
            </div>
        </div>
    </div>
    <div class="container font-monospace d-flex justify-content-evenly">
        <div class="text-center">
            <div class="h4">{{ $tasks }}</div>
            <div class="small">Tasks</div>
        </div>
        <div class="text-center">
            <div class="h4">{{ $users }}</div>
            <div class="small">Users</div>
        </div>
        <div class="text-center">
            <div class="h4">{{ $questions }}</div>
            <div class="small">Questions</div>
        </div>
        <div class="text-center">
            <div class="h4">{{ $milestones }}</div>
            <div class="small">Milestones</div>
        </div>
    </div>
    <div class="container col-3 my-5">
        <div class="card bg-transparent">
            <div class="card-body d-flex justify-content-between align-items-center">
                <div>Follow us on</div>
                <div>
                    <a class="me-3" href="https://twitter.com/taskord" target="_blank">
                        <img class="avatar-20" src="https://ik.imagekit.io/taskordimg/icons/twitter_4cXueyhRfH.svg"
                            loading=lazy />
                    </a>
                    <a class="me-3 href=" https://gitlab.com/yo" target="_blank">
                        <img class="avatar-20" src="https://ik.imagekit.io/taskordimg/icons/gitlab_j_ySNAHxP.svg"
                            loading=lazy />
                    </a>
                    <a href="https://taskord.com/product/taskord" target="_blank">
                        <img class="avatar-20" src="https://ik.imagekit.io/taskordimg/logo_FLhAmih_U.svg" loading=lazy />
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/api.blade.php
@extends('layouts.app')

@section('pageTitle', 'API ·')
@section('title', 'API ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
    <div class="container-md">
        <div class="card">
            <div class="card-header py-3">
                <span class="h5">API</span>
                <div>Taskord's Application Program Interface</div>
            </div>
            <div class="card-body">
                <div>
                    The Taskord API lets you build third-party apps for Taskord and integrate with existing ones.
                </div>
                <div class="mt-3">
                    The API uses GraphQL. It's a relatively new technology that lets you request all the data you need in
                    just one request. If you're unfamiliar with GraphQL we suggest you <a
                        href="https://graphql.org/learn">read up on it first</a>.
                </div>
                <div class="mt-3">
                    You can find all documentation and play around using our <a href="/graphiql">GraphiQL instance</a>.
                </div>
                <div class="mt-3">
                    Have a look at some <a href="#">Node.js example code</a> that creates a task and then completes it.
                </div>
                <div class="mt-3">
                    POST your GraphQL requests to https://taskord.com/graphql
                </div>
                <div class="mt-3">
                    The docs are on the right. Click through to Docs to find all types.
                </div>
                <div class="mt-3">
                    @auth
                        Get you <a href="{{ route('user.settings.api') }}">API token here</a>.
                    @else
                        Sign in to see your personal <a href="{{ route('user.settings.api') }}">API token</a>.
                    @endauth
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/contact.blade.php
@extends('layouts.app')

@section('pageTitle', 'Contact ·')
@section('title', 'Contact ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
    <div class="container-md">
        <div class="row justify-content-center" style="height:70vh">
            <div class="col-lg-7 mt-5">
                @auth
                    @php
                        $username = '@' . auth()->user()->username;
                        $email = urlencode(auth()->user()->email);
                        $url = 'https://tally.so/embed/5mVVam?username=' . $username . '&email=' . $email . '&transparentBackground=1';
                    @endphp
                    <iframe src="{{ $url }}" width="100%" height="100%" frameborder="0" marginheight="0"
                        marginwidth="0"></iframe>
                @else
                    <iframe src="https://tally.so/embed/63lL53?transparentBackground=1" width="100%" height="100%"
                        frameborder="0" marginheight="0" marginwidth="0"></iframe>
                @endauth
            </div>
        </div>
    </div>
@endsection

resources/views/pages/deals.blade.php
@extends('layouts.app')

@section('pageTitle', 'Deals ·')
@section('title', 'Deals ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
    <div class="container-md">
        <div class="card">
            <div class="card-header py-3">
                <span class="h5">Deals</span>
                <div>Discounts and special deals for Taskord members. Only available for patrons.</div>
                <div>
                    <a href="https://tally.so/r/63l4o3" target="_blank" rel="noreferrer">Add your product</a>
                </div>
                @can('staff.ops')
                    <button type="button" class="mt-2 btn btn-outline-success rounded-pill" data-bs-toggle="modal"
                        data-bs-target="#newQuestionModal">
                        <x-heroicon-o-plus class="heroicon" />
                        Add a Deal
                    </button>
                    <livewire:pages.create-deal />
                @endcan
            </div>
            <div class="card-body">
                @if (count($deals) === 0)
                    <div class="card-body text-center mt-3 mb-3">
                        <x-heroicon-o-gift class="heroicon heroicon-60px text-primary mb-2" />
                        <div class="h4">
                            No deals found
                        </div>
                    </div>
                @endif
                @foreach ($deals as $deal)
                    <div class="d-flex align-items-center {{ $loop->last ? '' : 'mb-5' }}">
                        <div>
                            <img loading=lazy class="rounded avatar-100" src="{{ $deal->logo }}" height="100" width="100"
                                alt="{{ $deal->name }}'s Logo" />
                        </div>
                        <div class="ms-4">
                            <span class="h4">
                                {{ $deal->name }}
                            </span>
                            <span class="h5">
                                <span class="align-text-top badge bg-success ms-1">{{ $deal->offer }}% OFF</span>
                            </span>
                            <div class="h6 mt-3">{{ $deal->description }}</div>
                            <div class="mt-2">
                                <a href="{{ $deal->website }}" target="_blank">{{ $deal->website }}</a>
                            </div>
                            @auth
                                @if (auth()->user()->is_patron)
                                    @if ($deal->coupon)
                                        <div class="mt-2">
                                            Coupon Code
                                            <code class="ms-2 fw-bold">
                                                {{ $deal->coupon }}
                                            </code>
                                        </div>
                                    @else
                                        <div class="mt-2 fw-bold">
                                            <a href="{{ $deal->referral }}" target="_blank">
                                                Click here to get your deal
                                            </a>
                                        </div>
                                    @endif
                                @else
                                    <div class="mt-2">
                                        <a class="text-secondary" href="{{ route('patron.home') }}">You must be a patron to
                                            see coupon code.</a>
                                    </div>
                                @endif
                            @endauth
                            @guest
                                <div class="mt-2">
                                    <a class="text-secondary" href="{{ route('login') }}">Login to view coupon code.</a>
                                </div>
                            @endguest
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

resources/views/pages/open.blade.php
@extends('layouts.app')

@section('pageTitle', 'Open ·')
@section('title', 'Open ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <div class="container-md">
        <div class="card">
            <div class="card-header py-3">
                <span class="h5">Open</span>
                <div>Analytics of Taskord</div>
            </div>
            <div class="card-body">
                <livewire:pages.open.all-tasks />
                <livewire:pages.open.completed-tasks />
                <livewire:pages.open.reputations />
            </div>
        </div>
    </div>
@endsection

resources/views/pages/patron.blade.php
@extends('layouts.app')

@section('pageTitle', 'Patron ·')
@section('title', 'Patron ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
    <div class="container-md">
        <div class="mb-4 text-center">
            <img loading=lazy src="https://ik.imagekit.io/taskordimg/patron_H2bHcQezM.svg" alt="Taskord Patron"
                width="100" />
        </div>
        <div class="card">
            <div class="card-header py-3">
                <span class="h5">Become a Patron</span>
                <div>Support Taskord by becoming a Patron.</div>
            </div>
            <div class="card-body">
                <div class="row align-items-center font-monospace">
                    <div class="col-lg-8">
                        <div class="fw-bold mb-3">You get the following benefits</div>
                        <ul>
                            <li>🌑 Enable Awesome Dark Mode</li>
                            <li>💬 Patrons only discussion to make it more meaningful</li>
                            <li>🔒 Make your tasks private and get personal things done</li>
                            <li>🤝 Show off your support with the Patron badge</li>
                            <li>👍 Fund on-going development of the platform and server fee</li>
                            <li>More coming soon...</li>
                        </ul>
                    </div>
                    <div class="col-sm d-grid">
                        @auth
                            @if (auth()->user()->is_patron and
            auth()->user()->patron()->count('id') ===
                1)
                                <div class="text-center">
                                    <div class="h5">
                                        ❤ You are already a patron!
                                    </div>
                                    <a class="text-primary" href="{{ route('user.settings.patron') }}">
                                        Go to settings
                                    </a>
                                </div>
                            @else
                                <a class="paddle_button btn btn-outline-primary rounded-pill" data-theme="none"
                                    data-product="619848" data-message="Support $5/month for Taskord!"
                                    data-email="{{ auth()->user()->email }}">
                                    Support $5/month
                                </a>
                                <a class="paddle_button btn mt-2 btn-outline-primary rounded-pill" data-theme="none"
                                    data-product="621377" data-message="Support $10/month for Taskord!"
                                    data-email="{{ auth()->user()->email }}">
                                    Support $10/month
                                </a>
                                <a class="paddle_button btn mt-2 btn-outline-primary rounded-pill" data-theme="none"
                                    data-product="621379" data-message="Support $20/month for Taskord!"
                                    data-email="{{ auth()->user()->email }}">
                                    Support $20/month
                                </a>
                                <a class="paddle_button btn mt-2 btn-outline-primary rounded-pill" data-theme="none"
                                    data-product="621380" data-message="Support $50/month for Taskord!"
                                    data-email="{{ auth()->user()->email }}">
                                    Support $50/month
                                </a>
                                <a class="paddle_button btn mt-2 btn-outline-primary rounded-pill" data-theme="none"
                                    data-product="629491" data-message="Support $100 onetime for lifetime pro in Taskord!"
                                    data-email="{{ auth()->user()->email }}">
                                    Support $100 onetime
                                </a>
                            @endif
                        @endauth
                        @guest
                            <a class="btn mt-2 btn-outline-success rounded-pill" href="{{ route('login') }}">
                                Login to support!
                            </a>
                        @endguest
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.paddle.com/paddle/paddle.js"></script>
    <script type="text/javascript">
        Paddle.Setup({
            vendor: 120187
        });
    </script>
@endsection

resources/views/pages/reputation.blade.php
@extends('layouts.app')

@section('pageTitle', 'Reputation ·')
@section('title', 'Reputation ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
    <div class="container-md">
        <div class="row justify-content-center mt-4">
            <div class="col-sm">
                <div class="card mb-4">
                    <div class="card-header py-3">
                        <span class="h5 text-success">Badges</span>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <span class="fw-bold">Beginner</span>
                            <span>0 to 500</span>
                        </div>
                        <div class="d-flex justify-content-between mt-2">
                            <span class="fw-bold">Novice</span>
                            <span>500 to 2500</span>
                        </div>
                        <div class="d-flex justify-content-between mt-2">
                            <span class="fw-bold">Intermediate</span>
                            <span>2500 to 5000</span>
                        </div>
                        <div class="d-flex justify-content-between mt-2">
                            <span class="fw-bold">Professional</span>
                            <span>5000 to 7500</span>
                        </div>
                        <div class="d-flex justify-content-between mt-2">
                            <span class="fw-bold">Expert</span>
                            <span>7500 to 10000</span>
                        </div>
                        <div class="d-flex justify-content-between mt-2">
                            <span class="fw-bold">Master</span>
                            <span>10000 to 20000</span>
                        </div>
                        <div class="d-flex justify-content-between mt-2">
                            <span class="fw-bold">GrandMaster</span>
                            <span>20000 to 50000</span>
                        </div>
                        <div class="d-flex justify-content-between mt-2">
                            <span class="fw-bold">Enlightened</span>
                            <span>50000 and above</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <livewire:user.reputations />
            </div>
        </div>
    </div>
@endsection